### ISSUE TITLE
'FloatingPointError: underflow encountered in logaddexp'  occurs when setting np.seterr(all='raise')

### ISSUE THREAD

**Issue by alatif-alatif** [hildensia/bayesian_changepoint_detection#24]
Hi,

I installed _bayesian_changepoint_detection_ from this github repository.

By setting (accidentally) `np.seterr(all='raise')`, I was able to cause the following exception. 

I am not sure whether this would have any relevance for the further processing, but I just wanted to draw attention to people working on  / with this library.

```python
/home/user/venv/env01/bin/python3.6 /home/user/PycharmProjects/project01/snippet.py
Use scipy logsumexp().
Traceback (most recent call last):
  File "/home/user/PycharmProjects/project01/snippet.py", line 68, in <module>
    Q, P, Pcp = offcd.offline_changepoint_detection(data, partial(offcd.const_prior, l=(len(data) + 1)), offcd.gaussian_obs_log_likelihood, truncate=-40)
  File "/home/user/experiments/original-unforked/bayesian_changepoint_detection/bayesian_changepoint_detection/offline_changepoint_detection.py", line 98, in offline_changepoint_detection
    Q[t] = np.logaddexp(P_next_cp, P[t, n-1] + antiG)
FloatingPointError: underflow encountered in logaddexp

Process finished with exit code 1

```

**Comment by estcarisimo** [comment]
Closing as obsolete. The `FloatingPointError` under `np.seterr(all='raise')` came from `np.logaddexp` underflowing in the NumPy offline recursion. The current implementation runs the offline recursion in PyTorch (float64, `logaddexp`/`logcumsumexp`), which does not consult NumPy's error state; a segment that is impossible under the prior is represented as `-inf` in log space on purpose and the changepoint probabilities stay finite. Checked today on `master` with `np.seterr(all='raise')` and warnings as errors on a 300-point series: no exception, evidence finite, changepoints at 99 and 199.
